import type { Scene } from "../domain/types";

const sharedAdultTasks: [string, string, string, string] = [
  "말해 주거나 보여 준 것을 고맙게 들어요.",
  "바로 말하지 못했어도 어린이의 잘못이 아니라고 알려 줘요.",
  "안전하고 편한 곳으로 함께 이동해요.",
  "필요한 다른 어른과 함께 계속 도와요.",
];

export const sceneBank: Scene[] = [
  {
    id: "hear-my-turn",
    title: "내 생각도 들을 차례예요",
    eyebrow: "교실 이야기",
    fictionalNotice: "여기 나오는 인물과 일은 모두 만든 이야기예요.",
    imageSrc: "/learning/classroom-turn.webp",
    panels: [
      {
        id: "turn-1",
        icon: "🧑‍🤝‍🧑",
        place: "모둠 활동 시간",
        narration: "하루가 새 놀이 방법을 이야기하려고 해요.",
        dialogue: "제 생각도 말해 볼래요.",
        altText: "네 어린이가 둥근 책상에서 이야기하는 가상 교실 장면",
      },
      {
        id: "turn-2",
        icon: "💭",
        place: "이야기가 빠르게 이어져요",
        narration: "다른 친구들의 말이 계속 이어져 하루의 차례가 오지 않아요.",
        dialogue: "제 말도 들어 주면 좋겠어요.",
        altText: "하루가 자기 생각을 말할 차례를 기다리는 가상 장면",
      },
    ],
    rightIds: ["participation", "self-respect"],
    rightOptions: ["participation", "self-respect", "protection"],
    actionOptions: ["say-boundary", "move-away", "show-help-card", "ask-adult", "ask-another-adult", "skip-scene"],
    factPhrases: ["모둠에서 제 생각을 말할 차례가 오지 않아요.", "친구들의 말이 계속 이어지고 있어요."],
    boundaryPhrases: ["제 생각도 말하고 싶어요."],
    helpPhrases: ["제 말을 들을 수 있게 도와주세요.", "함께 이야기 순서를 정해 주세요."],
    adultResponse: {
      message: "말해 줘서 고마워. 네 생각도 중요해. 함께 이야기 순서를 정해 볼게.",
      responsibilities: sharedAdultTasks,
    },
    anotherAdult: "처음 찾아간 어른이 지금 바로 돕기 어렵다면, 가까이에 있는 다른 선생님이나 보호자에게 같은 문장을 보여 줘도 돼요.",
    sensitivityTier: 1,
    sourceIds: ["unicef-crc", "unicef-korea-education"],
    reviewVersion: "review-copy-1",
    reviewStatus: "review-ready",
    reviewedAt: "2026-07-17",
  },
  {
    id: "stop-unwanted-nickname",
    title: "싫은 별명은 멈춰 주세요",
    eyebrow: "쉬는 시간 이야기",
    fictionalNotice: "여기 나오는 인물과 일은 모두 만든 이야기예요.",
    imageSrc: "/learning/nickname-boundary.webp",
    panels: [
      {
        id: "nickname-1",
        icon: "🎒",
        place: "교실 앞 복도",
        narration: "친구가 민우를 원하지 않는 별명으로 불러요.",
        dialogue: "그 별명은 그만 불러 줘.",
        altText: "민우가 복도에서 친구에게 별명을 멈춰 달라고 말하는 가상 장면",
      },
      {
        id: "nickname-2",
        icon: "🫤",
        place: "조금 뒤",
        narration: "민우가 멈춰 달라고 했지만 친구가 다시 같은 별명을 불러요.",
        dialogue: "계속 들으니 힘들어요.",
        altText: "민우가 반복되는 별명 때문에 도움을 생각하는 가상 장면",
      },
    ],
    rightIds: ["self-respect", "protection"],
    rightOptions: ["self-respect", "protection", "participation"],
    actionOptions: ["say-boundary", "move-away", "show-help-card", "ask-adult", "ask-another-adult", "skip-scene"],
    factPhrases: ["멈춰 달라고 했는데 별명을 계속 불러요.", "원하지 않는 별명을 반복해서 들어요."],
    boundaryPhrases: ["저는 그 별명으로 불리고 싶지 않아요."],
    helpPhrases: ["멈출 수 있게 도와주세요.", "지금 함께 가 주세요."],
    adultResponse: {
      message: "말해 줘서 고마워. 바로 말하지 못했어도 네 잘못이 아니야. 내가 함께 멈추도록 도울게.",
      responsibilities: sharedAdultTasks,
    },
    anotherAdult: "한 어른이 상황을 잘 알아듣지 못해도 포기할 필요는 없어요. 다른 선생님이나 보호자에게 다시 보여 주세요.",
    sensitivityTier: 2,
    sourceIds: ["unicef-crc", "unicef-korea-education"],
    reviewVersion: "review-copy-1",
    reviewStatus: "review-ready",
    reviewedAt: "2026-07-17",
  },
  {
    id: "ask-before-sharing-photo",
    title: "내 사진은 먼저 물어봐 주세요",
    eyebrow: "사진 이야기",
    fictionalNotice: "여기 나오는 인물과 일은 모두 만든 이야기예요.",
    imageSrc: "/learning/photo-consent.webp",
    panels: [
      {
        id: "photo-1",
        icon: "📷",
        place: "만들기 활동 뒤",
        narration: "친구가 서윤이와 작품을 함께 찍었어요.",
        dialogue: "사진을 단체방에 올릴래.",
        altText: "친구가 작품과 서윤이의 사진을 찍은 가상 장면",
      },
      {
        id: "photo-2",
        icon: "📱",
        place: "사진을 올리기 전",
        narration: "친구는 서윤이에게 물어보지 않고 사진을 올리려고 해요.",
        dialogue: "제 사진은 먼저 물어봐 주세요.",
        altText: "서윤이가 사진을 올리기 전에 동의를 구해 달라고 생각하는 가상 장면",
      },
    ],
    rightIds: ["privacy", "self-respect"],
    rightOptions: ["privacy", "self-respect", "protection"],
    actionOptions: ["say-boundary", "move-away", "show-help-card", "ask-adult", "ask-another-adult", "skip-scene"],
    factPhrases: ["제 사진을 묻지 않고 올리려고 해요.", "제가 나온 사진을 단체방에 보내려고 해요."],
    boundaryPhrases: ["제 사진은 올리지 않았으면 해요."],
    helpPhrases: ["올리지 않도록 도와주세요.", "사진을 어떻게 해야 할지 함께 확인해 주세요."],
    adultResponse: {
      message: "알려 줘서 고마워. 네 사진은 네 의견을 먼저 들어야 해. 올리지 않도록 함께 확인할게.",
      responsibilities: sharedAdultTasks,
    },
    anotherAdult: "처음 물어본 어른이 바쁘다면 사진을 보내기 전에 다른 선생님이나 보호자에게 화면을 보여 줘도 돼요.",
    sensitivityTier: 1,
    sourceIds: ["unicef-crc", "unicef-korea-education"],
    reviewVersion: "review-copy-1",
    reviewStatus: "review-ready",
    reviewedAt: "2026-07-17",
  },
  {
    id: "do-not-send-personal-info",
    title: "개인정보는 보내지 않아요",
    eyebrow: "온라인 놀이 이야기",
    fictionalNotice: "여기 나오는 채팅과 인물은 모두 만든 이야기예요.",
    imageSrc: "/learning/online-privacy.webp",
    panels: [
      {
        id: "info-1",
        icon: "🎮",
        place: "온라인 게임 채팅",
        narration: "모르는 사람이 지우에게 학교 이름과 사진을 물어봐요.",
        dialogue: "학교랑 사진을 보내 줄래?",
        altText: "온라인 게임의 가상 채팅에서 모르는 사람이 정보를 묻는 장면",
      },
      {
        id: "info-2",
        icon: "🔒",
        place: "보내기 전 멈춤",
        narration: "지우는 정보를 보내지 않고 화면을 닫거나 어른에게 보여 줄 수 있어요.",
        dialogue: "같이 확인해 주세요.",
        altText: "지우가 정보를 보내지 않고 도움을 요청하는 가상 장면",
      },
    ],
    rightIds: ["privacy", "protection"],
    rightOptions: ["privacy", "protection", "self-respect"],
    actionOptions: ["move-away", "show-help-card", "ask-adult", "ask-another-adult", "skip-scene"],
    factPhrases: ["모르는 사람이 제 정보와 사진을 달라고 했어요.", "게임 채팅에서 학교 이름을 물어봤어요."],
    boundaryPhrases: [],
    helpPhrases: ["같이 확인해 주세요.", "정보를 보내지 않도록 지금 함께해 주세요."],
    adultResponse: {
      message: "화면을 보여 줘서 고마워. 정보를 보내지 않고 나에게 온 것은 좋은 도움 방법이야. 이제 내가 함께 확인할게.",
      responsibilities: sharedAdultTasks,
    },
    anotherAdult: "첫 번째 어른이 바로 보지 못하면 채팅을 계속하지 말고, 가까이에 있는 다른 어른에게 화면을 보여 줘도 돼요.",
    sensitivityTier: 2,
    sourceIds: ["unicef-crc", "unicef-korea-education", "mohw-112"],
    reviewVersion: "review-copy-1",
    reviewStatus: "review-ready",
    reviewedAt: "2026-07-17",
  },
  {
    id: "stop-scary-play",
    title: "놀이가 무섭게 계속돼요",
    eyebrow: "운동장 이야기",
    fictionalNotice: "여기 나오는 인물과 일은 모두 만든 이야기예요.",
    imageSrc: "/learning/safe-play.webp",
    panels: [
      {
        id: "play-1",
        icon: "⚽",
        place: "운동장 공놀이",
        narration: "공놀이가 점점 거칠어져 유나가 그만하고 싶어 해요.",
        dialogue: "이제 그만할래요.",
        altText: "유나가 거칠어진 공놀이를 그만하고 싶은 가상 장면",
      },
      {
        id: "play-2",
        icon: "🛝",
        place: "운동장 옆",
        narration: "놀이는 계속되지만 유나는 나와서 어른과 함께 이동할 수 있어요.",
        dialogue: "지금 함께 나가 주세요.",
        altText: "유나가 놀이에서 나와 도움을 요청하는 가상 장면",
      },
    ],
    rightIds: ["safe-play", "protection"],
    rightOptions: ["safe-play", "protection", "self-respect"],
    actionOptions: ["say-boundary", "move-away", "show-help-card", "ask-adult", "ask-another-adult", "skip-scene"],
    factPhrases: ["놀이가 거칠어져 계속하고 싶지 않아요.", "그만하고 싶지만 놀이가 계속되고 있어요."],
    boundaryPhrases: ["저는 이제 그만하고 싶어요."],
    helpPhrases: ["지금 여기에서 함께 나가 주세요.", "안전한 곳으로 같이 가 주세요."],
    adultResponse: {
      message: "알려 줘서 고마워. 놀이를 멈추고 나와도 괜찮아. 내가 안전한 곳으로 함께 갈게.",
      responsibilities: sharedAdultTasks,
    },
    anotherAdult: "처음 부른 어른이 듣지 못했다면 더 크게 말해야만 하는 것은 아니에요. 다른 어른에게 카드나 문장을 보여 주세요.",
    sensitivityTier: 2,
    sourceIds: ["unicef-crc", "unicef-korea-education"],
    reviewVersion: "review-copy-1",
    reviewStatus: "review-ready",
    reviewedAt: "2026-07-17",
  },
];
